on: push
name: Validate API swagger documentation
jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test
    steps:
      # first checkout your code
      - name: Checkout
        uses: actions/checkout@v3
      # then use redocly-cli-github-action
      - name: Redocly CLI Test
        uses: fluximus-prime/redocly-cli-github-action@v1
        with:
          args: 'lint spec/'


